
project_id = "hryurntaljdisohawpqf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_users = false

[functions.ai-alert-system]
verify_jwt = false

[functions.analyze-ticket]
verify_jwt = false

[functions.process-notifications]
verify_jwt = false

[functions.notification-scheduler]
verify_jwt = false

[functions.system-log]
verify_jwt = false

[functions.typebot-webhook]
verify_jwt = false

[functions.typebot-ticket-message]
verify_jwt = false

[functions.franqueado-login]
verify_jwt = false

[functions.suggest-reply]
verify_jwt = false

[functions.ticket-ai-chat]
verify_jwt = false

[functions.lambda-models]
verify_jwt = false

[functions.debug-env]
verify_jwt = false

[functions.test-openai-key]
verify_jwt = false

[functions.colaborador-signup]
verify_jwt = false

[functions.test-notifications]
verify_jwt = false

[functions.process-pending-notifications]
verify_jwt = false

[functions.process-response]
verify_jwt = false

[functions.autoatendimento_calendario]
verify_jwt = false

[functions.autoatendimento_midias]
verify_jwt = false

[functions.autoatendimento_ticket]
verify_jwt = false

[functions.autoatendimento_nao_sei_senha]
verify_jwt = false

[functions.autoatendimento_ouvidoria]
verify_jwt = false

[functions.autoatendimento_manuais]
verify_jwt = false

[functions.outras_opcoes]
verify_jwt = false

[functions.autoatendimento]
verify_jwt = false

[functions.bot_base]
verify_jwt = false

[functions.zapi-whatsapp]
verify_jwt = false

[functions.personalizado_menu]
verify_jwt = false

[functions.emergencia_menu]
verify_jwt = false

[functions.menu_principal]
verify_jwt = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
