project_id = "hryurntaljdisohawpqf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_users = false

[functions.ai-alert-system]
verify_jwt = false

[functions.analyze-ticket]
verify_jwt = false

[functions.analyze-team-tickets-bulk]
verify_jwt = false

[functions.autoatendimento]
verify_jwt = false


[functions.autoatendimento_manuais]
verify_jwt = false

[functions.autoatendimento_midias]
verify_jwt = false

[functions.autoatendimento_nao_sei_senha]
verify_jwt = false

[functions.autoatendimento_ouvidoria]
verify_jwt = false

[functions.autoatendimento_ticket]
verify_jwt = false

[functions.autoatendimento_calendario]
verify_jwt = false

[functions.bot_base_1]
verify_jwt = false

[functions.ticket_equipes]
verify_jwt = false

[functions.suporte_dfcom]
verify_jwt = false

[functions.colaborador-signup]
verify_jwt = false

[functions.create-internal-notification]
verify_jwt = false

[functions.create-ticket]
verify_jwt = false

[functions.crises-ai-analyst]
verify_jwt = false

[functions.debug-env]
verify_jwt = false

[functions.delete-ticket]
verify_jwt = false

[functions.emergencia_menu]
verify_jwt = false

[functions.faq-suggest]
verify_jwt = false

[functions.franqueado-login]
verify_jwt = false

[functions.get-documentos-list]
verify_jwt = false

[functions.kb-audit]
verify_jwt = false

[functions.kb-create-memory]
verify_jwt = false

[functions.kb-update-document]
verify_jwt = false

[functions.kb-upsert-document]
verify_jwt = false

[functions.lambda-models]
verify_jwt = false

[functions.menu_principal]
verify_jwt = false

[functions.move-ticket]
verify_jwt = false

[functions.notification-scheduler]
verify_jwt = false

[functions.outras_opcoes]
verify_jwt = false

[functions.personalizado_menu]
verify_jwt = false

[functions.process-notifications]
verify_jwt = false

[functions.process-pending-notifications]
verify_jwt = false

[functions.process-response]
verify_jwt = false

[functions.process-ticket-response]
verify_jwt = false

[functions.test-resposta-ticket]
verify_jwt = false

[functions.test-button-click]
verify_jwt = false

[functions.test-complete-flow]
verify_jwt = false

[functions.test-instance-routing]
verify_jwt = false

[functions.regenerate-all-embeddings]
verify_jwt = false

[functions.regenerate-embeddings]
verify_jwt = false

[functions.suggest-reply]
verify_jwt = false

[functions.system-log]
verify_jwt = false

[functions.test-crisis-detection]
verify_jwt = false

[functions.test-embedding-fix]
verify_jwt = false

[functions.test-notifications]
verify_jwt = false

[functions.test-openai-key]
verify_jwt = false

[functions.test-zapi-credentials]
verify_jwt = false

[functions.test-semantic-rag]
verify_jwt = false

[functions.test-webhook]
verify_jwt = false

[functions.ticket-ai-chat]
verify_jwt = false

[functions.ticket-completion-moderator]
verify_jwt = false

[functions.typebot-ticket-message]
verify_jwt = false

[functions.typebot-webhook]
verify_jwt = false

[functions.update-ticket]
verify_jwt = false

[functions.vincular-tickets-existentes]
verify_jwt = false

[functions.zapi-send-media]
verify_jwt = false

[functions.zapi-whatsapp]
verify_jwt = false

[functions.generate-daily-report]
verify_jwt = false

[functions.sync-atendentes]
verify_jwt = false

[functions.sla-processor]
verify_jwt = false

[functions.test-group-notification]
verify_jwt = false

[functions.debug-notifications]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = true

[functions.register-push-subscription]
verify_jwt = true

[functions.import-unidades-from-csv]
verify_jwt = true

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324